# Enigma OS bootloader (Calamares). systemd-boot on UEFI, GRUB on BIOS.
---
efiBootLoader: "systemd-boot"
kernel: "/vmlinuz-linux-cachyos"
img: "/initramfs-linux-cachyos.img"
fallback: "/initramfs-linux-cachyos-fallback.img"

timeout: "5"
bootloaderEntryName: "Enigma OS"
kernelLine: ", with Enigma Kernel"
fallbackKernelLine: ", with Enigma Kernel (fallback)"

grubInstall: "grub"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
installEFIFallback: true
