# Enable the essential services on the installed system.
---
services:
  - name: NetworkManager
    mandatory: false
  - name: sddm
    mandatory: false
  - name: apparmor
    mandatory: false

targets:
  - name: graphical
    mandatory: true

disable: []
