title   Enigma OS (Live — Load to RAM)
sort-key live-copytoram
linux   /arch/boot/x86_64/vmlinuz-linux-cachyos
initrd  /arch/boot/x86_64/initramfs-linux-cachyos.img
options archisobasedir=arch archisodevice=UUID=%ARCHISO_UUID% copytoram cow_spacesize=2G modprobe.blacklist=sp5100_tco,gpio_ich
