title   Enigma OS (Live — Amnesic)
sort-key live-amnesic
linux   /arch/boot/x86_64/vmlinuz-linux-cachyos
initrd  /arch/boot/x86_64/initramfs-linux-cachyos.img
options archisobasedir=arch archisodevice=UUID=%ARCHISO_UUID% cow_spacesize=2G modprobe.blacklist=sp5100_tco,gpio_ich console=tty0 console=ttyS0,115200n8
