---
modules-search: [ local ]

instances:
  - id: root
    module: partition
    config: modules/partition.conf
  - id: users
    module: users
    config: modules/users.conf
  - id: bootloader
    module: bootloader
    config: modules/bootloader.conf
  - id: packages
    module: packages
    config: modules/packages.conf
  - id: finished
    module: finished

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - hwclock
    - systemd-conf
    - grubcfg
    - bootloader
    - packages
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - removeuser
    - umount
  - show:
    - finished

branding: enigmaos

prompt-install: true
dont-clear-password-fields: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
